SELECT *, 
       (CUSTO_FINANCEIRO / PESO) AS CUSTO_UNITARIO,
       CASE
           WHEN (CUSTO_FINANCEIRO / PESO) > 5.41 THEN 'Ponto'
           WHEN (CUSTO_FINANCEIRO / PESO) < 5.41 THEN 'OK'
           ELSE 'N/A'
       END AS CLASSIFICACAO
FROM VW_AUDIT_RM_GERENCIAMENTO_ESTOQUE
WHERE COD_ESTABELECIMENTO = 'R621'
  AND DATA BETWEEN '2025-09-01' AND '2025-09-30'
  AND TIPO_OPERACAO = '1.7.006'
  AND (CUSTO_FINANCEIRO / PESO) = 'Ponto' 