SELECT
    P.COD_ITEM AS Cod_Item,
    P.DESCR_ITEM AS Descricao,
    MAX(KDX.DATA) AS Ultima_compra,
    DATEDIFF(DAY, MAX(KDX.DATA), GETDATE()) AS dias_sem_giro,
    CASE
        WHEN DATEDIFF(DAY, MAX(KDX.DATA), GETDATE()) < 180 THEN 'Produto OK'
        WHEN DATEDIFF(DAY, MAX(KDX.DATA), GETDATE()) BETWEEN 180 AND 720 THEN 'Baixo Giro'
        WHEN DATEDIFF(DAY, MAX(KDX.DATA), GETDATE()) > 720 THEN 'Produto Obsoleto' 
        ELSE 'N/A'
    END AS Giro_de_Estoque,
    CASE
        WHEN SUM(KDX.QTD) < 0 THEN 'Saída'
        WHEN SUM(KDX.QTD) > 0 THEN 'Entrada'
        ELSE 'Sem_Movimentacao'
    END AS Movimentacao
FROM
    VW_AUDIT_RM_ESTOQUE_PRODUTO AS P
INNER JOIN
    VW_AUDIT_RM_GERENCIAMENTO_ESTOQUE AS KDX ON P.COD_ITEM = KDX.COD_ITEM
WHERE
    (P.DEPOSITO LIKE '%BTN%' OR KDX.DEPOSITO LIKE '%BTN%')
    AND (P.COD_ESTABELECIMENTO = 'R351' OR KDX.COD_ESTABELECIMENTO = 'R351')
GROUP BY
    P.COD_ITEM, P.DESCR_ITEM
