SELECT
    FAT.COD_ESTABELECIMENTO,
    FAT.COD_CLIENTE,
    FAT.NOME_CLIENTE,
    FAT.DATA_NOTA_FISCAL,
    FAT.NUM_NOTA_FISCAL,
    SUM(FAT.VALOR) AS TOTAL_VALOR
FROM
 	VW_AUDIT_RM_ORDENS_VENDA AS FAT
LEFT JOIN
 	VW_AUDIT_RM_GERENCIAMENTO_ESTOQUE AS KDX
    	ON FAT.COD_ESTABELECIMENTO = KDX.COD_ESTABELECIMENTO
   	AND FAT.DATA_NOTA_FISCAL = KDX.DATA
   	AND FAT.CFOP = KDX.CFOP
   	AND FAT.NUM_NOTA_FISCAL = KDX.NUM_NOTA_FISCAL 
WHERE FAT.CFOP IN ('5.102', '5.104', '5.106', '5.114',
                   '5.403', '5.405', '5.655',
                   '6.102', '6.108', '6.403', '6.404')
  AND FAT.NUM_NOTA_FISCAL NOT LIKE '%EST%'
  AND FAT.NUM_NOTA_FISCAL NOT LIKE '%NFD%'
  AND KDX.NUM_NOTA_FISCAL IS NULL 
  AND FAT.DATA BETWEEN '2025-08-01' AND '2025-08-31'
GROUP BY
    FAT.COD_ESTABELECIMENTO,
    FAT.COD_CLIENTE,
    FAT.NOME_CLIENTE,
    FAT.DATA_NOTA_FISCAL,
    FAT.NUM_NOTA_FISCAL;