SELECT *, CAST(GETDATE() AS DATE) AS DATA_ATUAL,
       DATEDIFF(DAY, DATA_VENCIMENTO, CAST(GETDATE() AS DATE)) AS DIAS_ATRASO
FROM 
	VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE 
	COD_ESTABELECIMENTO = 'R281'
	AND DATA_TRANSACAO BETWEEN '2024-09-01' AND '2025-08-31'
	AND STATUS = 'ABERTO' 
	AND PERFIL_LANC NOT IN ('INS', 'INR', 'IRR', 'PIS', 'ICM', 'IRF', 'IRJ', 'CSL', 'COF', 'RET', 'FGT', 'ASL', 'SIN', 'SAL', 'ISS', 'DFB', 'TEL', 'ARD', 'FIN', 'ARL', 'AFE', 'SEG')
	AND NUM_NOTA_FISCAL NOT LIKE '%EST%' 
	AND VALOR_MOEDA > 0
	AND DATEDIFF(DAY, DATA_VENCIMENTO, CAST(GETDATE() AS DATE)) > 0


