SELECT 
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    SUM(VALOR_PAGO) AS VALOR_TOTAL_PAGO,
    METODO_PAGAMENTO
FROM 
    VW_AUDIT_RM_TRANSACOES_FECHADAS
WHERE 
    COD_ESTABELECIMENTO = 'R241'
    AND DATA_TRANSACAO BETWEEN '2025-09-01' AND '2025-09-30'
    AND METODO_PAGAMENTO LIKE '%REC_CXA%'
GROUP BY
    COD_ESTABELECIMENTO,
    COD_CLIENTE,
    NOME_CLIENTE,
    METODO_PAGAMENTO
HAVING 
    SUM(VALOR_PAGO) > 1200