SELECT *
FROM VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE COD_ESTABELECIMENTO IN ('R281', 'R282', 'R283')
  AND DATA_TRANSACAO BETWEEN '2024-09-01' AND '2025-08-31'
  AND (
    TEXTO_TRANSACAO LIKE '%AJUDANTE%' OR
    TEXTO_TRANSACAO LIKE '%CHAPEIRO%' OR
    TEXTO_TRANSACAO LIKE '%CHAPA%' OR
    TEXTO_TRANSACAO LIKE '%Ajudante%' OR
    TEXTO_TRANSACAO LIKE '%Chapeiro%' OR
    TEXTO_TRANSACAO LIKE '%FREELANCER%' OR
    TEXTO_TRANSACAO LIKE '%Freelancer%'
  )
 