SELECT 
    COD_ESTABELECIMENTO,
    DEPOSITO,
    COD_ITEM,
    DESCR_ITEM,
    VALOR_CUSTO,
    COUNT(*) as QTD_REGISTROS
FROM 
    VW_AUDIT_RM_ESTOQUE_PRODUTO
WHERE 
    ESTOQUE <= 0
    AND DEPOSITO LIKE '%BTN%'
    AND VALOR_CUSTO <> 0	
GROUP BY 
    COD_ESTABELECIMENTO, 
    DEPOSITO, 
    COD_ITEM,
    DESCR_ITEM,
    VALOR_CUSTO
ORDER BY 
    COD_ESTABELECIMENTO,
    DEPOSITO,
    COD_ITEM