SELECT 
    D.*,
    CASE 
        WHEN D.VALOR > 0 THEN 'Débito'
        WHEN D.VALOR < 0 THEN 'Crédito'
        ELSE 'N/A'
    END AS TIPO_LANCAMENTO
FROM 
    VW_AUDIT_RM_TRANSACOES_CONTA_CONTABIL AS D
JOIN 
    VW_AUDIT_RM_TRANSACOES_CONTA_CONTABIL AS C  
    ON D.TIPO_TRANSACAO = C.TIPO_TRANSACAO
    AND D.COD_ESTABELECIMENTO = C.COD_ESTABELECIMENTO
WHERE 
    D.COD_ESTABELECIMENTO = 'R281'
    AND D.DATA_TRANSACAO BETWEEN '2025-08-01' AND '2025-08-31'
    AND D.USUARIO_CRIACAO_LOG NOT IN ('adm.d365.lotes', 'Admin');