SELECT *, 
       CAST(GETDATE() AS DATE) AS DATA_ATUAL,
       DATEDIFF(DAY, DATA_VENCIMENTO, CAST(GETDATE() AS DATE)) AS DIAS_ATRASO
FROM VW_AUDIT_RM_TRANSACOES_FORNECEDOR
WHERE 
  COD_ESTABELECIMENTO = 'R241'
  AND DATA_TRANSACAO BETWEEN '2024-07-01' AND '2025-07-31'
  AND PERFIL_LANC = 'AFO'
  AND DATEDIFF(DAY, DATA_VENCIMENTO, CAST(GETDATE() AS DATE)) > 30